#key:空格+值
#server:
#  port: 8080

spring:
  application:
    # 配置服务名称
    name: time-ode
  # 数据库连接信息
  datasource:
    url: jdbc:mysql://127.0.0.1:3310/time-ode?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    mail:
      host: smtp.qq.com
      username: 3555290257@qq.com
      password: 你的授权码
      properties:
        mail:
          smtp:
            ssl:
              enable: true



demo:
  abc:
    application:
      name: ${spring.application.name}
      version: ${JAVA_HOME}

#mybatis:
#  #配置映射文件位置
#  mapper-location: classpath:mapper/*.xml
#  #配置别名,有无都可以
##  type-aliases-package: com.carrot.timeode.model.entity
#  type-aliases-package: com.carrot.timeode.domain

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    com.carrot.timeode.mapper: debug
    org.mybatis: debug
    org.apache.ibatis: debug

#分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#进行分页时ai添加
server:
  port: 8080

#server:
#  port: 8888
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3310/bigdata?serverTimezone=Asia/Shanghai&characterEncoding=utf8
#    username: root
#    password: 123456
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.carrot.bigdata20250902.domain
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  level:
#    com:
#      carrot:
#        bigdata20250902:
#          mapper: debug
#    org:
#      apache:
#        ibatis: trace
#    java:
#      sql:
#        Connection: debug
#        Statement: debug
#        PreparedStatement: debug